spring:
  application:
    name: RagDocSupport
  thymeleaf:
    cache: false
  mvc:
    async:
      request-timeout: 1800000
  datasource:
    url: jdbc:sqlite:data/tasks.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  docker:
    compose:
      lifecycle-management: start-only
  ai:
    mcp:
      server:
        name: rag-doc-support
        version: 1.0.0
        type: SYNC
        protocol: STREAMABLE
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: qwen3-embedding:8b

server:
  port: 8080

qdrant:
  host: localhost
  port: 6334
  collection-name: doc-chunks

crawler:
  sleep-time-ms: 100
  timeout-ms: 30000
  retry-times: 2
